title: Mark1626 Home Page
markdown: kramdown
url: "https://mark1626.github.io"
baseurl: "/"

# for atom feed
author:
  name: Nimalan aka Mark1626

show_excerpts: false

theme: minima

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

header_pages:
  - about.md
  - projects.md

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: mark1626
    keybase: mark854
    codepen: mark854

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["README.md", "Gemfile", "Gemfile.lock"]
