title: Mark1626 Home Page
markdown: kramdown
url: "https://mark1626.github.io"
baseurl: "/"

# for atom feed
author: Nimalan aka Mark1626

theme: minima

plugins:
  - jekyll-paginate-v2
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

header_pages:
  - about.md
  - blog.md
  - books.md
  - projects.md

minima:
  social_links:
    github: mark1626
    keybase: mark854

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  title: ':title - page :num'
  sort_field: 'date'
  category: 'posts'

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["sitemap.xml", "feed.xml", "content.js", "README.md"]
