title: Mark1626 Home Page
github_username: \@mark1626
description: >- 
  An unsettling mind on an endless search for inspiration.
url: "https://mark1626.github.io"
remote_theme: tareqdandachi/jekyll-shell-theme
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jemoji
highlighter: rouge
font-size: large
header_pages:
  - index.md
  - about.md
  - blog.md
  - projects.md
