title: Mark1626 Home Page
markdown: kramdown
url: "https://mark1626.github.io"
baseurl: "/"

# for atom feed
author:
  name: Nimalan aka Mark1626

site:
  author:
    name: Nimalan aka Mark1626

theme: minima

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

header_pages:
  - about.md
  - blog.md
  - books.md
  - projects.md

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["sitemap.xml", "feed.xml", "content.js", "README.md"]
